name = "UQM"
author = "Octal"
version = "1.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17de33020f2865b091420844ceecc6c2c4083a1706c51fab0a78675910ea02ae"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
