name = "UQM"
author = "Octal"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d032f897f6fce15bc06c14aedbcdc98d0e4b056d925cc7e3485e5015e3a6eb55"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
