name = "UQM"
author = "Octal"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d3f105961f494d48615b78877e53f28d4db6c154c98a0393f9aee8dd0cf528e"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
