name = "UQM"
author = "Octal"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5953c9f02ee86472e981951e27abf36547f54935ecdbece393b4c74be97738e"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
