name = "UQM"
author = "Octal"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a1d0f3ee9a1b73b33dd12fb64388b2262e7ae323e167f047c3999b21443895f"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
