name = "UQM"
author = "Octal"
version = "1.0.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62608bd711a47c5f1bd06f13ae301a7446f38de51dece23e9a9939baa488101c"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
