name = "UQM"
author = "Octal"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf85c73507fe45d9fa64ebc40527411563ed116601018e14eab30a5a9f8f725b"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
