name = "UQM"
author = "Octal"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44a3c28a2c58898b2fc317dbde5b1e810c2f0cc90bfef5b651c1eae8cc05e0d9"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
