name = "UQM"
author = "Octal"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bfd4a2f052e0c562b6adb3fd6eb89e62192d96bcf3f1d0397d21cbeb56b3129"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
