name = "UQM"
author = "Octal"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b63bd385ea3ee0f04a25dda937723118a3b6bdb4f8ccde977062d5fa0379556"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
