name = "UQM"
author = "Octal"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0391bc408dad3df095a125fdf3a88b0b536682ff1f40309b1bd0f6b215f93d7e"

[versions]
minecraft = "1.19"
quilt = "0.17.2-beta.1"
