name = "UQM"
author = "Octal"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd4b73bf40534a890e201bbae07e65dac5aad5fb91617f3e8e73af1817f3a183"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
