name = "UQM"
author = "Octal"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ab348720413c9bd263c76a67b2f23911c1ffe41a7ddd8988c7b8f164b10959c"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
