name = "UQM"
author = "Octal"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d619cbdee0fdbe60eab530379dec43034c9f024e4f18301a8a1e117657de43af"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
