name = "UQM"
author = "Octal"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9700fb73c7aa97a71828e6d57320ed8f5d6244dc310ece33e8ed272a05a2b782"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
