name = "UQM"
author = "Octal"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2583090cc3b125da50a2e504c3347e06d596d7c84a323b19a1b79b91c5daa8db"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
