name = "UQM"
author = "Octal"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f1e4a1fe7cdf5b0bfc3225eb636a2b02044334ec145311a5ab08716449989cf"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
