name = "UQM"
author = "Octal"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7e962c9bbc14ef04c469a67409fd26ef62f65f4138459948ac3d2b0734feeb5"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
