name = "UQM"
author = "Octal"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5aaefbdf9cf27aff776598ed56839b663d5470f03f1381ac1d82c2488ec3d00"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
