name = "UQM"
author = "Octal"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b842128d7e232dfe10a5fb71d13b4f9018314eee67f745b0ecbe53e22b0c005"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
