name = "UQM"
author = "Octal"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e486099360b388424ae6d2779e0e729974d5e4164af95f360ed68a1d4c1d0b33"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
