name = "UQM"
author = "Octal"
version = "1.0.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96c6c0523339af0da4ac1e3a091bd8a6f221ba26072e01e9982f44f6eef0fef0"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
