name = "UQM"
author = "Octal"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12d69ac4b5cce856c3e5c96a13eda930235ebf98bbf635c0ade31162000ad9c9"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
