name = "Architecture Extensions"
filename = "architecture_extensions-0.3.4+1.19.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/YyhsabMU/versions/v0.3.4+1.19/architecture_extensions-0.3.4%2B1.19.jar"
hash-format = "sha1"
hash = "9448dd7e1fef47642a54442138ac13d4c7cb9211"

[update]
[update.modrinth]
mod-id = "YyhsabMU"
version = "ES1WLcin"
