name = "BoatJump"
filename = "boatjump-1.0.0-1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/uv58eYCk/versions/1.0.0/boatjump-1.0.0-1.18.2.jar"
hash-format = "sha1"
hash = "adcb82013bad23983de3c1aa41eca0dae26bba39"

[update]
[update.modrinth]
mod-id = "uv58eYCk"
version = "wbDwIrka"
