name = "Fabric Waystones"
filename = "wraith-waystones-3.0.1+mc1.19.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/sTZr7NVo/versions/3.0.1+mc1.19/wraith-waystones-3.0.1%2Bmc1.19.jar"
hash-format = "sha1"
hash = "c3e39b20ac58cd8688cfd9502d7f14614220043f"

[update]
[update.modrinth]
mod-id = "sTZr7NVo"
version = "vTHlNQAW"
