name = "Plymouth: Anti-Xray"
filename = "ply-anti-xray-0.0.0-rc.5+mc.1.18.2-rc1.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/6Zrbdphe/versions/0.0.0-rc.5+mc.1.18.2-rc1/ply-anti-xray-0.0.0-rc.5%2Bmc.1.18.2-rc1.jar"
hash-format = "sha1"
hash = "cbf7b4df15fd058ff081bc0eb40a0d19ede20919"

[update]
[update.modrinth]
mod-id = "6Zrbdphe"
version = "AJeHID4e"
