name = "TooManyOrigins"
filename = "TooManyOrigins-1.19-0.6.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/xDjN28OB/versions/v0.6.1+1.19-fabric/TooManyOrigins-1.19-0.6.1.jar"
hash-format = "sha1"
hash = "ca0e4a51bafdb900442a4649ac5ac64bbe9d9996"

[update]
[update.modrinth]
mod-id = "xDjN28OB"
version = "jUCyJlIq"
